# Exercise 5
### Jan Kesting, Felix Fleischle - 26.5.2023 - Group 1 Jeong Yun Choi

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.sparse import diags

#### 1. Implementing Gaussian elimination
To implement gaussian elimination, we have to take our matrix equation and transform the left matrix into a unitary matrix, such that our solution vector is equal to the resulting vector on the right. Our general matrix equation would be M*x = y. We're not sure how much of this code is actually meant to be part of 3. :)

In [2]:
def gaussian_elimination(M, y):
    # First, do elementary operations until we have only the upper triangle left
    # --> We iterate through the matrix
    for i in range(len(M)-1):
        f1 = M[i+1,i]/M[i,i]
        M[i+1,i+1] -= f1 * M[i,i+1]
        y[i+1] -= f1 * y[i]
        M[i+1,i] = 0
        
    # Then, we eliminate the upper entries to get a diagonal matrix
    for j in range(len(M)-1, 0, -1):
        f2 = M[j-1,j]/M[j,j]
        y[j-1] -= f2 * y[j]
        M[j-1,j] = 0
        
    # And finally we transform the diagonal matrix into a unitary matrix
    for k in range(len(M)):
        y[k] = y[k]/M[k,k]
        M[k,k] = 1
        
    return M,y

2. Implementing backwards subsitution

In [3]:
def backwards_subst(M,x):
    y = np.ones(len(x))
    
    for i in range(len(x)):
        sum = 0
        for j in range(len(x)):
            sum += M[i,j] * x[j]
        y[i] = sum
    return y

3. Writing a subroutine that finds the solution when given values of a, b, c, y

In [16]:
def solver(a, b, c, y, extractmatrix):
    # Build the matrix M out of the given information
    # using scipy.sparse.diags
    # The extractmatrix parameter is a bool that is used to extract the matrix in part 5.
    
    list_of_diagonals = [a, b, c]
    M = diags(list_of_diagonals, [-1, 0, 1]).toarray()
    
    if extractmatrix:
        return M
    else:
        # Use the function defined in 1. to get the solution
        return gaussian_elimination(M,y)

4. Test our code with given values

In [36]:
N = 10
a = -1 * np.ones(N-1)
b = 1.5 * np.ones(N)
c = -1 * np.ones(N-1)
y = 0.1 * np.ones(N)
y_copy = 0.1 * np.ones(N)


M_end, y_end = solver(a,b,c,y,False)
print(M_end)
print(y_end)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[ 0.09565217  0.04347826 -0.13043478 -0.33913043 -0.47826087 -0.47826087
 -0.33913043 -0.13043478  0.04347826  0.09565217]


5. Using our backwards substition code to test the deviation from the original y

In [38]:
# Get the Matrix M again
M_original = solver(a,b,c,y,True)

# x is equal to y_end
y_original = backwards_subst(M_original, y_end)

y_diff = y_original - y_copy
print("Deviation:\n",y_diff)

Deviation:
 [ 0.00000000e+00  1.38777878e-17  2.77555756e-17 -2.77555756e-17
  2.77555756e-17 -2.77555756e-17  5.55111512e-17 -2.77555756e-17
  1.38777878e-17  2.77555756e-17]
