In [10]:
import numpy as np

In [14]:
# small program to solve the system for given epsilon with gauss jordan
def solve_equation(epsilon):
    # Setup matrix
    M = np.array([[epsilon, 1/3, 1/3], [1/3, 1/3, 1/6]])
    
    # Perform gauss jordan
    M[0,:] = M[0,:] / M[0,0]
    M[1,:] = M[1,:] - M[0,:]*M[1,0]/M[0,0]
    M[1,:] = M[1,:] / M[1,1]
    M[0,:] = M[0,:] - M[1,:] * M[0,1]/M[1,1]
    
    return M[:,-1]

# Solve the system
eps = 1e-12
x = solve_equation(eps)
print("x\n",x)

x
 [-0.5  1. ]


In [15]:
# Reinsert solution into the matrix
A = np.array([[eps, 1/3],[1/3,1/3]])
y = np.array([[1/3, 1/6]])
y_re = np.dot(A,x)

print("A * x\n", y_re)

A * x
 [0.33333333 0.16666667]


In [19]:
from scipy.linalg import lu as ludcmp
from scipy.linalg import solve_triangular as lubksb
from scipy.linalg import inv

eps = 1e-12
A = np.array([[eps, 1/3],[1/3,1/3]])
y = np.array([1/3, 1/6])

p, l, u = ludcmp(A)
print("P\n", p)
print("L\n", l)
print("U\n", u)

# perform backsub
x_bs = lubksb(u,y)
print("x_bs\n",x_bs)

# Test via reinsertion
y_re_bs = np.dot(np.dot(inv(p),A),x_bs)
print("A * x_bs \n", y_re_bs)
print("y - y_re_bs \n", y- y_re_bs)

P
 [[0. 1.]
 [1. 0.]]
L
 [[1.e+00 0.e+00]
 [3.e-12 1.e+00]]
U
 [[0.33333333 0.33333333]
 [0.         0.33333333]]
x_bs
 [0.5 0.5]
A * x_bs 
 [0.33333333 0.16666667]
y - y_re_bs 
 [ 0.00000000e+00 -1.00000563e-12]
